# .github/workflows/python-tests.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Make all shell scripts executable
        run: |
          find . -type f -name '*.sh' -exec chmod +x {} \;

      - name: Run shell tests
        run: |
          set -e 
          for script in $(find . -type f -name '*.sh' | sort); do
            echo "Running $script"
            timeout 60s sudo $script
          done
